import { fileURLToPath, URL } from "node:url";

import js from "@eslint/js";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import { defineFlatConfig } from "eslint-define-config";
import simpleSortPlugin from "eslint-plugin-simple-import-sort";
import sortKeysPlugin from "eslint-plugin-sort-keys";
import globals from "globals";

const root = fileURLToPath(new URL(".", import.meta.url));

export default defineFlatConfig([
  {
    files: ["**/*.ts"],
    languageOptions: {
      ecmaVersion: "latest",
      globals: {
        ...globals.builtin,
        ...globals.es2021,
        ...globals.node,
        ...globals.nodeBuiltin,
      },
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        parser: tsParser,
        project: "./tsconfig.json",
        sourceType: "module",
        tsconfigRootDir: root,
      },
      sourceType: "module",
    },
    linterOptions: {
      noInlineConfig: false,
      reportUnusedDisableDirectives: false,
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
      "simple-sort": simpleSortPlugin,
      "sort-keys": sortKeysPlugin,
    },
    rules: {
      ...js.configs.all.rules,
      ...tsPlugin.configs.all.rules,
      "@typescript-eslint/ban-ts-comment": ["off"],
      "@typescript-eslint/ban-types": ["off"],
      "@typescript-eslint/class-methods-use-this": ["off"],
      "@typescript-eslint/comma-dangle": ["off"],
      "@typescript-eslint/consistent-type-exports": ["off"],
      "@typescript-eslint/explicit-function-return-type": ["off"],
      "@typescript-eslint/explicit-module-boundary-types": ["off"],
      "@typescript-eslint/indent": [
        "off",
        2,
        {
          SwitchCase: 1,
        },
      ],
      "@typescript-eslint/lines-between-class-members": ["off"],
      "@typescript-eslint/naming-convention": ["off"],
      "@typescript-eslint/no-confusing-void-expression": ["off"],
      "@typescript-eslint/no-empty-function": ["off"],
      "@typescript-eslint/no-empty-interface": ["off"],
      "@typescript-eslint/no-extraneous-class": ["off"],
      "@typescript-eslint/no-floating-promises": ["off"],
      "@typescript-eslint/no-magic-numbers": ["off"],
      "@typescript-eslint/no-namespace": ["off"],
      "@typescript-eslint/no-redundant-type-constituents": ["off"],
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": ["off"],
      "@typescript-eslint/no-unsafe-call": ["off"],
      "@typescript-eslint/no-unsafe-return": ["off"],
      "@typescript-eslint/no-unused-expressions": ["off"],
      "@typescript-eslint/no-unused-vars": ["off"],
      "@typescript-eslint/no-useless-constructor": ["off"],
      "@typescript-eslint/no-useless-empty-export": ["off"],
      "@typescript-eslint/object-curly-spacing": ["off"],
      "@typescript-eslint/prefer-destructuring": ["off"],
      "@typescript-eslint/prefer-namespace-keyword": ["off"],
      "@typescript-eslint/prefer-readonly": ["off"],
      "@typescript-eslint/prefer-readonly-parameter-types": ["off"],
      "@typescript-eslint/require-await": ["off"],
      "@typescript-eslint/restrict-template-expressions": ["off"],
      "@typescript-eslint/sort-type-constituents": ["off"],
      "@typescript-eslint/space-before-function-paren": ["off"],
      "array-callback-return": ["off"],
      "arrow-body-style": ["off"],
      curly: ["off"],
      "func-names": ["off"],
      "func-style": ["off"],
      "id-length": ["off"],
      "max-lines-per-function": ["off"],
      "multiline-comment-style": ["off"],
      "new-cap": ["off"],
      "no-console": [
        "error",
        {
          allow: [
            "assert",
            "clear",
            "countReset",
            "debug",
            "dir",
            "dirxml",
            "error",
            "group",
            "groupCollapsed",
            "groupEnd",
            "info",
            "log",
            "profile",
            "profileEnd",
            "table",
            "time",
            "timeEnd",
            "timeLog",
            "timeStamp",
            "trace",
            "warn",
          ],
        },
      ],
      "no-duplicate-imports": ["off"],
      "no-empty-pattern": ["off"],
      "no-magic-numbers": ["off"],
      "no-new": ["off"],
      "no-plusplus": ["off"],
      "no-promise-executor-return": ["off"],
      "no-ternary": ["off"],
      "no-undef": ["off"],
      "no-undefined": ["off"],
      "no-underscore-dangle": ["off"],
      "no-warning-comments": ["off"],
      "one-var": ["off"],
      "simple-sort/exports": ["error"],
      "simple-sort/imports": ["error"],
      "sort-imports": ["off"],
      "sort-keys": ["off"],
      "sort-keys/sort-keys-fix": ["error"],
    },
    settings: {},
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      globals: {
        ...globals.builtin,
        ...globals.es2021,
        ...globals.node,
        ...globals.nodeBuiltin,
      },
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
      },
      sourceType: "module",
    },
    linterOptions: {
      noInlineConfig: false,
      reportUnusedDisableDirectives: false,
    },
    plugins: {
      "simple-sort": simpleSortPlugin,
      "sort-keys": sortKeysPlugin,
    },
    rules: {
      ...js.configs.all.rules,
      "array-callback-return": ["off"],
      "no-console": [
        "error",
        {
          allow: ["debug"],
        },
      ],
      "no-magic-numbers": ["off"],
      "no-underscore-dangle": ["off"],
      "one-var": ["off"],
      "simple-sort/exports": ["error"],
      "simple-sort/imports": ["error"],
      "sort-imports": ["off"],
      "sort-keys": ["off"],
      "sort-keys/sort-keys-fix": ["error"],
    },
    settings: {},
  },
  {
    ignores: ["dist", "node_modules"],
  },
]);
